"""0003

Revision ID: bcc84a6b0640
Revises: fd396579a46a
Create Date: 2024-09-15 03:57:40.207795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcc84a6b0640'
down_revision: Union[str, None] = 'fd396579a46a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('faces_image_id_fkey', 'faces', type_='foreignkey')
    op.create_foreign_key(None, 'faces', 'images', ['image_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('images_task_id_fkey', 'images', type_='foreignkey')
    op.create_foreign_key(None, 'images', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.create_foreign_key('images_task_id_fkey', 'images', 'tasks', ['task_id'], ['id'])
    op.drop_constraint(None, 'faces', type_='foreignkey')
    op.create_foreign_key('faces_image_id_fkey', 'faces', 'images', ['image_id'], ['id'])
    # ### end Alembic commands ###
